namespace Bemo

module Localization_English =
    let strings = dict [
        ("Programs", "Programs")
        ("Refresh", "Refresh")
        ("ShowAllSettings", "Show all settings")
        ("ProcessName", "Process Name")
        ("Name", "Name")
        ("EnableTabs", "Tabs")
        ("EnableAutoGrouping", "Auto Grouping")
        ("Category", "Category ")

        ("Appearance", "Appearance")
        ("Tab Height", "Tab Height")
        ("Tab Width (Max)", "Tab Width (Max)")
        ("Pinned Tab Width", "Pinned Tab Width")
        ("PinnedWidthIconOnly", "Icon Only")
        ("PinnedWidthSpecify", "Specify Width")
        ("Tab Overlap", "Tab Overlap")
        ("Indent Normal", "Distance from edge when tabs up")
        ("Indent Flipped", "Distance from edge when tabs down")
        ("MenuDarkMode", "Menu Dark Mode")
        ("SettingsDialogDarkMode", "Settings Dialog Dark Mode")

        ("ColorTheme", "Color Theme")
        ("SaveAs", "Save As")
        ("EnterThemeName", "Enter theme name:")
        ("SaveThemeTitle", "Save Color Theme")
        ("EditThemeTitle", "Edit Color Theme")
        ("EditThemePrompt", "Enter a new theme name:")
        ("DeleteThemeHint", "Clear the name and press OK to delete this theme.")

        ("ClipboardOperations", "Clipboard")
        ("CopySelectedTheme", "Copy Selected Theme")
        ("CopyAllPresetThemes", "Copy All Preset Themes")
        ("CopyAllSavedThemes", "Copy All Saved Themes")
        ("PasteThemes", "Paste Color Themes")

        ("TabColorHeader", "Tab Color")
        ("TabColor", "Tab Color")
        ("TextColor", "Text Color")
        ("BorderColor", "Border Color")
        ("Inactive", "Inactive")
        ("MouseOver", "Mouse Over")
        ("Active", "Active")
        ("Flash", "Flash")

        ("Behavior", "Behavior")
        ("RunAtStartup", "Run WindowTabs at startup")
        ("HideInactiveTabs", "Fade out tabs on inactive windows")
        ("IsTabbingEnabledForAllProcessesByDefault", "Enable tabs for all programs by default")
        ("EnableCtrlNumberHotKey", "Enable Ctrl+1, ...Ctrl+9 to active tab")
        ("EnableHoverActivate", "Enable mouse hover to activate tab")

        ("TabPositionByDefault", "Tab position")
        ("HideTabsWhenDownByDefault", "Hide tabs when positioned at bottom")
        ("HideTabsNever", "Never hide")
        ("HideTabsWhenDown", "Hide after specified time")
        ("HideTabsDelayMilliseconds", "Wait time (ms)")
        ("HideTabsOnClick", "Hide when clicking active tab icon")

        ("HideTabsOnFullscreen", "Hide tabs when window is fullscreen")
        ("SnapTabHeightMargin", "Add tab height margin when snapping")
        ("NextTab", "Next Tab")
        ("PrevTab", "Previous Tab")

        ("Workspace", "Workspace")
        ("New", "New")
        ("Restore", "Restore")
        ("Edit", "Edit")
        ("Remove", "Remove")
        ("MatchType", "Match Type")
        ("Title", "Title")

        ("Diagnostics", "Diagnostics")
        ("Reset", "Reset")

        ("NewLaunchMenu", "New launch : execute {0}")
        ("NewTabInGroup", "New tab : right of this tab ({0})")
        ("NewWindowPositionMenu", "New window (position)")
        ("NewWindowLinkGroupMenu", "New window (link to group)")
        ("NewLaunchErrorUWP", "Failed to start new window.\n\nThis application ({0}) is a UWP app and\ncannot be launched directly.\n\nPlease launch it from the Start menu instead.")
        ("NewLaunchErrorProcess", "Failed to launch process.\n\nPath: {0}\nError: {1}")
        ("NewLaunchErrorUnexpected", "Unexpected error starting process:\n{0}")

        ("MoveEdgeMenu", "Move")
        ("MoveEdgeLeft", "Left Edge")
        ("MoveEdgeRight", "Right Edge")
        ("MoveEdgeTop", "Top Edge")
        ("MoveEdgeBottom", "Bottom Edge")
        ("SnapLeft", "Snap Left")
        ("SnapRight", "Snap Right")
        ("SnapTop", "Snap Top")
        ("SnapBottom", "Snap Bottom")
        ("MoveCorner", "Corner")
        ("MoveEdgeTopLeft", "Top Left")
        ("MoveEdgeTopRight", "Top Right")
        ("MoveEdgeBottomLeft", "Bottom Left")
        ("MoveEdgeBottomRight", "Bottom Right")
        ("SnapPercent", "Snap {0}%")
        ("SnapLeftPercent", "Left")
        ("SnapRightPercent", "Right")
        ("SnapTopPercent", "Top")
        ("SnapBottomPercent", "Bottom")
        ("SnapTopLeftPercent", "Top Left")
        ("SnapTopRightPercent", "Top Right")
        ("SnapBottomLeftPercent", "Bottom Left")
        ("SnapBottomRightPercent", "Bottom Right")
        ("SnapCenter", "Center")
        ("SnapCenterHorizontal", "Center Horizontally")
        ("SnapCenterVertical", "Center Vertically")
        ("SnapMaximizeDisplay", "Snap Display")
        ("SnapMaximizeDesktop", "Snap Desktop")
        ("MovePositionOther", "Position Other")
        ("PositionMoveMenu", "Position Move")
        ("SnapOtherMenu", "Snap Other")
        ("SamePositionThisDisplay", "Same position on this display")
        ("Display", "Display")
        ("Left", "Left")
        ("Right", "Right")
        ("Up", "Up")
        ("Down", "Down")
        ("Main", "Main")

        ("DockingTabGroupToGroup", "Link to another group")

        ("CloseTabMenu", "Close Tab")
        ("CloseTab", "Close tab : {0}")
        ("CloseTabsToTheRightFormat", "Close {0} tabs to the right")
        ("CloseTabsToTheLeftFormat", "Close {0} tabs to the left")
        ("TabSingular", "Tab")
        ("TabPlural", "Tabs")
        ("CloseOtherTabs", "Close other tabs")
        ("CloseAllTabs", "Close all tabs")

        ("SnapTabMarginMenu", "Tab Margin When Snapping")
        ("SnapTabMarginTop", "Add margin at top")

        ("TabAlignMenu", "Tab Position")
        ("AlignAllTopLeft", "Align all tabs to Left")
        ("AlignAllTopRight", "Align all tabs to Right")
        ("AlignTabSubMenu", "Individual Tab Alignment")
        ("AlignThisTabLeft", "Align this tab to Left")
        ("AlignThisTabRight", "Align this tab to Right")
        ("AlignLeftTabsChange", "Align {0} left tab(s) to {1}")
        ("AlignRightTabsChange", "Align {0} right tab(s) to {1}")
        ("AlignTopLeft", "Left")
        ("AlignTopRight", "Right")

        ("PinTabMenu", "Tab Pin")
        ("PinThisTab", "Pin this tab")
        ("UnpinThisTab", "Unpin this tab")
        ("PinLeftTabsFormat", "Pin {0} left tab(s)")
        ("UnpinLeftTabsFormat", "Unpin {0} left tab(s)")
        ("PinRightTabsFormat", "Pin {0} right tab(s)")
        ("UnpinRightTabsFormat", "Unpin {0} right tab(s)")

        ("TabColorMenu", "Tab Color Settings")
        ("TabColorThisTab", "This tab color : {0}")
        ("TabColorClearThisTab", "Clear this tab color")
        ("TabColorApplyLeft", "Left {0} tab(s) color")
        ("TabColorClearLeft", "Clear left {0} tab(s) color")
        ("TabColorApplyRight", "Right {0} tab(s) color")
        ("TabColorClearRight", "Clear right {0} tab(s) color")
        ("TabColorRed", "Red")
        ("TabColorBlue", "Blue")
        ("TabColorGreen", "Green")
        ("TabColorYellow", "Yellow")
        ("TabColorPurple", "Purple")
        ("TabColorOrange", "Orange")
        ("TabColorPink", "Pink")
        ("TabColorRedUnderline", "Red Underline")
        ("TabColorBlueUnderline", "Blue Underline")
        ("TabColorGreenUnderline", "Green Underline")
        ("TabColorYellowUnderline", "Yellow Underline")
        ("TabColorPurpleUnderline", "Purple Underline")
        ("TabColorOrangeUnderline", "Orange Underline")
        ("TabColorPinkUnderline", "Pink Underline")
        ("TabColorRedBorder", "Red Border")
        ("TabColorBlueBorder", "Blue Border")
        ("TabColorGreenBorder", "Green Border")
        ("TabColorYellowBorder", "Yellow Border")
        ("TabColorPurpleBorder", "Purple Border")
        ("TabColorOrangeBorder", "Orange Border")
        ("TabColorPinkBorder", "Pink Border")

        ("TabNameEdit", "Tab Name")
        ("RenameTab", "Rename tab")
        ("ResetTabName", "Reset tab name")

        ("TabDetachAndSplit", "Tab Detach and Split")
        ("DetachAndMovePosTab", "Detach this tab and reposition")
        ("DetachTabSamePosition", "Same position")
        ("DetachAndDockingTabToGroup", "Detach this tab and link to another group")
        ("SplitRightTabsToPositionFormat", "Split right {0} tabs and reposition")
        ("SplitRightTabsToGroupFormat", "Split right {0} tabs and link to group")
        ("SplitLeftTabsToPositionFormat", "Split left {0} tabs and reposition")
        ("SplitLeftTabsToGroupFormat", "Split left {0} tabs and link to group")
        ("MoveTabGroupFormat", "{0} {1}: {2}")

        ("SystemMenu", "System")
        ("SystemCopyExePath", "Copy {0} path")
        ("SystemCopyWindowTitle", "Copy window title : {0}")
        ("SystemOpenExeFolder", "Open folder of {0}")
        ("SystemKillProcess", "Force kill this process")

        ("SettingsMenu", "Settings...")

        ("Settings", "Settings...")
        ("Disable", "Disable")
        ("RestartWindowTabs", "Restart WindowTabs")
        ("CloseWindowTabs", "Close WindowTabs")
    ]
