namespace Bemo

module Localization_English =
    let strings = dict [
        ("Programs", "Programs")
        ("Refresh", "Refresh")
        ("Name", "Name")
        ("EnableTabs", "Tabs")
        ("EnableAutoGrouping", "Auto Grouping")
        ("Category", "Category ")

        ("Appearance", "Appearance")
        ("Height", "Height")
        ("Max Width", "Max Width")
        ("Overlap", "Overlap")
        ("Indent Normal", "Distance from edge when tabs up")
        ("Indent Flipped", "Distance from edge when tabs down")
        ("MenuDarkMode", "Menu Dark Mode")

        ("ColorTheme", "Color Theme")
        ("SaveAs", "Save As")
        ("EnterThemeName", "Enter theme name:")
        ("SaveThemeTitle", "Save Color Theme")
        ("EditThemeTitle", "Edit Color Theme")
        ("EditThemePrompt", "Enter a new theme name:")
        ("DeleteThemeHint", "Clear the name and press OK to delete this theme.")

        ("ClipboardOperations", "Clipboard")
        ("CopySelectedTheme", "Copy Selected Theme")
        ("CopyAllPresetThemes", "Copy All Preset Themes")
        ("CopyAllSavedThemes", "Copy All Saved Themes")
        ("PasteThemes", "Paste Color Themes")

        ("TabColorHeader", "Tab Color")
        ("TabColor", "Tab Color")
        ("TextColor", "Text Color")
        ("BorderColor", "Border Color")
        ("Inactive", "Inactive")
        ("MouseOver", "Mouse Over")
        ("Active", "Active")
        ("Flash", "Flash")

        ("Behavior", "Behavior")
        ("RunAtStartup", "Run WindowTabs at startup")
        ("HideInactiveTabs", "Fade out tabs on inactive windows")
        ("IsTabbingEnabledForAllProcessesByDefault", "Enable tabs for all programs by default")
        ("EnableCtrlNumberHotKey", "Enable Ctrl+1, ...Ctrl+9 to active tab")
        ("EnableHoverActivate", "Enable mouse hover to activate tab")
        ("MakeTabsNarrowerByDefault", "Toggle tab width on active tab icon double-click")

        ("TabPositionByDefault", "Tab position")
        ("AlignLeft", "Left")
        ("AlignCenter", "Center")
        ("AlignRight", "Right")
        ("HideTabsWhenDownByDefault", "Hide tabs when positioned at bottom")
        ("HideNever", "Never hide")
        ("HideWhenDown", "Hide after specified time")
        ("HideTabsDelayMilliseconds", "Wait time (ms)")
        ("HideOnDoubleClick", "Hide when double-clicking active tab")

        ("HideTabsOnFullscreen", "Hide tabs when window is fullscreen")
        ("NextTab", "Next Tab")
        ("PrevTab", "Previous Tab")

        ("Workspace", "Workspace")
        ("New", "New")
        ("Restore", "Restore")
        ("Edit", "Edit")
        ("Remove", "Remove")
        ("MatchType", "Match Type")
        ("Title", "Title")

        ("Diagnostics", "Diagnostics")
        ("Reset", "Reset")

        ("NewTab", "New tab")

        ("MoveEdgeLeft", "Left Edge Move")
        ("MoveEdgeRight", "Right Edge Move")
        ("MoveEdgeTop", "Top Edge Move")
        ("MoveEdgeBottom", "Bottom Edge Move")
        ("MoveEdgeTopLeft", "Top Left Edge Move")
        ("MoveEdgeTopRight", "Top Right Edge Move")
        ("MoveEdgeBottomLeft", "Bottom Left Edge Move")
        ("MoveEdgeBottomRight", "Bottom Right Edge Move")
        ("MoveCorner", "Move Corner")
        ("SnapLeft", "Left Edge Snap")
        ("SnapRight", "Right Edge Snap")
        ("SnapLeftPercent", "Left Edge Snap {0}%")
        ("SnapRightPercent", "Right Edge Snap {0}%")
        ("SnapTop", "Top Edge Snap")
        ("SnapTopPercent", "Top Edge Snap {0}%")
        ("SnapBottom", "Bottom Edge Snap")
        ("SnapBottomPercent", "Bottom Edge Snap {0}%")
        ("MovePositionOther", "Reposition Other")
        ("SnapPercent", "Snap {0}%")
        ("Display", "Display")
        ("Left", "Left")
        ("Right", "Right")
        ("Up", "Up")
        ("Down", "Down")
        ("Main", "Main")

        ("CloseTab", "Close tab")
        ("CloseTabsToTheRightFormat", "Close tabs to the right ({0} {1})")
        ("CloseTabsToTheLeftFormat", "Close tabs to the left ({0} {1})")
        ("TabSingular", "Tab")
        ("TabPlural", "Tabs")
        ("CloseOtherTabs", "Close other tabs in this group")
        ("CloseAllTabs", "Close all tabs in this group")

        ("TabWidthChange", "Tab Width")
        ("IconOnly", "Icon Only")
        ("IconAndText", "Icon and Text")

        ("TabNameEdit", "Tab Name")
        ("RenameTab", "Rename tab")
        ("ResetTabName", "Reset tab name")

        ("TabDetachAndSplit", "Tab Detach and Split")
        ("DetachAndMovePosTab", "Detach this tab and reposition")
        ("DetachTabSamePosition", "Same position")
        ("DetachAndDockingTabToGroup", "Detach this tab and link to another group")
        ("SplitRightTabsToPositionFormat", "Split right side ({0} tabs) and reposition")
        ("SplitRightTabsToGroupFormat", "Split right side ({0} tabs) and link to group")
        ("SplitLeftTabsToPositionFormat", "Split left side ({0} tabs) and reposition")
        ("SplitLeftTabsToGroupFormat", "Split left side ({0} tabs) and link to group")
        ("MoveTabGroupFormat", "{0} {1}: {2}")
        ("MovePosTabGroup", "Reposition this tab group")
        ("DockingTabGroupToGroup", "Link this tab group to another group")

        ("SettingsMenu", "Settings...")

        ("Settings", "Settings...")
        ("Disable", "Disable")
        ("RestartWindowTabs", "Restart WindowTabs")
        ("CloseWindowTabs", "Close WindowTabs")
    ]
