namespace Bemo

module Localization_English =
    let strings = dict [
        ("Programs", "Programs")
        ("Refresh", "Refresh")
        ("ShowAllSettings", "Show all settings")
        ("ProcessName", "Process Name")
        ("Name", "Name")
        ("EnableTabs", "Tabs")
        ("EnableAutoGrouping", "Auto Grouping")
        ("Category", "Category ")

        ("Appearance", "Appearance")
        ("Tab Height", "Tab Height")
        ("Tab Width (Max)", "Tab Width (Max)")
        ("Pinned Tab Width", "Pinned Tab Width")
        ("PinnedWidthIconOnly", "Icon Only")
        ("PinnedWidthSpecify", "Specify Width")
        ("Tab Overlap", "Tab Overlap")
        ("Indent Normal", "Distance from edge when tabs up")
        ("Indent Flipped", "Distance from edge when tabs down")
        ("MenuDarkMode", "Menu Dark Mode")
        ("EnableSplitMoveSnapMenu", "Combined Move and Snap Menu")

        ("ColorTheme", "Color Theme")
        ("SaveAs", "Save As")
        ("EnterThemeName", "Enter theme name:")
        ("SaveThemeTitle", "Save Color Theme")
        ("EditThemeTitle", "Edit Color Theme")
        ("EditThemePrompt", "Enter a new theme name:")
        ("DeleteThemeHint", "Clear the name and press OK to delete this theme.")

        ("ClipboardOperations", "Clipboard")
        ("CopySelectedTheme", "Copy Selected Theme")
        ("CopyAllPresetThemes", "Copy All Preset Themes")
        ("CopyAllSavedThemes", "Copy All Saved Themes")
        ("PasteThemes", "Paste Color Themes")

        ("TabColorHeader", "Tab Color")
        ("TabColor", "Tab Color")
        ("TextColor", "Text Color")
        ("BorderColor", "Border Color")
        ("Inactive", "Inactive")
        ("MouseOver", "Mouse Over")
        ("Active", "Active")
        ("Flash", "Flash")

        ("Behavior", "Behavior")
        ("RunAtStartup", "Run WindowTabs at startup")
        ("HideInactiveTabs", "Fade out tabs on inactive windows")
        ("IsTabbingEnabledForAllProcessesByDefault", "Enable tabs for all programs by default")
        ("EnableCtrlNumberHotKey", "Enable Ctrl+1, ...Ctrl+9 to active tab")
        ("EnableHoverActivate", "Enable mouse hover to activate tab")

        ("TabPositionByDefault", "Tab position")
        ("AlignLeft", "Align Left")
        ("AlignRight", "Align Right")
        ("AlignAllTopLeft", "Align all tabs to Left")
        ("AlignAllTopRight", "Align all tabs to Right")
        ("HideTabsWhenDownByDefault", "Hide tabs when positioned at bottom")
        ("HideTabsNever", "Never hide")
        ("HideTabsWhenDown", "Hide after specified time")
        ("HideTabsDelayMilliseconds", "Wait time (ms)")
        ("HideTabsOnClick", "Hide when clicking active tab icon")

        ("HideTabsOnFullscreen", "Hide tabs when window is fullscreen")
        ("SnapTabHeightMargin", "Add tab height margin when snapping")
        ("NextTab", "Next Tab")
        ("PrevTab", "Previous Tab")

        ("Workspace", "Workspace")
        ("New", "New")
        ("Restore", "Restore")
        ("Edit", "Edit")
        ("Remove", "Remove")
        ("MatchType", "Match Type")
        ("Title", "Title")

        ("Diagnostics", "Diagnostics")
        ("Reset", "Reset")

        ("NewTab", "New tab : execute {0}")

        ("MoveEdgeLeft", "Move Left Edge")
        ("MoveEdgeRight", "Move Right Edge")
        ("MoveEdgeTop", "Move Top Edge")
        ("MoveEdgeBottom", "Move Bottom Edge")
        ("SnapLeft", "└Snap")
        ("SnapRight", "└Snap")
        ("SnapTop", "└Snap")
        ("SnapBottom", "└Snap")
        ("MoveSnapMenuCombined.MoveEdgeLeft", "Move Left")
        ("MoveSnapMenuCombined.MoveEdgeRight", "Move Right")
        ("MoveSnapMenuCombined.MoveEdgeTop", "Move Top")
        ("MoveSnapMenuCombined.MoveEdgeBottom", "Move Bottom")
        ("MoveSnapMenuCombined.SnapLeft", "Snap")
        ("MoveSnapMenuCombined.SnapRight", "Snap")
        ("MoveSnapMenuCombined.SnapTop", "Snap")
        ("MoveSnapMenuCombined.SnapBottom", "Snap")
        ("MoveCorner", "Corner")
        ("MoveEdgeTopLeft", "Top Left")
        ("MoveEdgeTopRight", "Top Right")
        ("MoveEdgeBottomLeft", "Bottom Left")
        ("MoveEdgeBottomRight", "Bottom Right")
        ("SnapPercent", "Snap {0}%")
        ("SnapLeftPercent", "Left")
        ("SnapRightPercent", "Right")
        ("SnapTopPercent", "Top")
        ("SnapBottomPercent", "Bottom")
        ("SnapTopLeftPercent", "Top Left")
        ("SnapTopRightPercent", "Top Right")
        ("SnapBottomLeftPercent", "Bottom Left")
        ("SnapBottomRightPercent", "Bottom Right")
        ("SnapCenter", "Center")
        ("SnapCenterHorizontal", "Center Horizontally")
        ("SnapCenterVertical", "Center Vertically")
        ("SnapMaximizeDisplay", "Snap Display")
        ("SnapMaximizeDesktop", "Snap Desktop")
        ("MovePositionOther", "Move Other")
        ("Display", "Display")
        ("Left", "Left")
        ("Right", "Right")
        ("Up", "Up")
        ("Down", "Down")
        ("Main", "Main")

        ("DockingTabGroupToGroup", "Link to another group")

        ("CloseTabMenu", "Close Tab")
        ("CloseTab", "Close tab : {0}")
        ("CloseTabsToTheRightFormat", "Close {0} tabs to the right")
        ("CloseTabsToTheLeftFormat", "Close {0} tabs to the left")
        ("TabSingular", "Tab")
        ("TabPlural", "Tabs")
        ("CloseOtherTabs", "Close other tabs")
        ("CloseAllTabs", "Close all tabs")

        ("SnapTabMarginMenu", "Tab Margin When Snapping")
        ("SnapTabMarginTop", "Add margin at top")
        ("TabPositionMenu", "Tab Position")
        ("PinTabMenu", "Tab Pin")
        ("PinThisTab", "Pin this tab")
        ("UnpinThisTab", "Unpin this tab")
        ("PinAllTabs", "Pin all tabs")
        ("UnpinAllTabs", "Unpin all tabs")
        ("PinLeftTabsFormat", "Pin {0} left tab(s) in {1}")
        ("PinRightTabsFormat", "Pin {0} right tab(s) in {1}")
        ("UnpinLeftTabsFormat", "Unpin {0} left tab(s) in {1}")
        ("UnpinRightTabsFormat", "Unpin {0} right tab(s) in {1}")
        ("AlignGroupTopLeft", "left-aligned")
        ("AlignGroupTopRight", "right-aligned")

        ("TabColorMenu", "Tab Color Settings")
        ("TabColorReset", "Reset this tab color : {0}")
        ("TabColorResetAll", "Reset all tab colors")
        ("TabColorApplyLeft", "Apply color to {0} left tab(s)")
        ("TabColorApplyRight", "Apply color to {0} right tab(s)")
        ("TabColorResetLeft", "Reset color of {0} left tab(s)")
        ("TabColorResetRight", "Reset color of {0} right tab(s)")
        ("TabColorRed", "Red")
        ("TabColorBlue", "Blue")
        ("TabColorGreen", "Green")
        ("TabColorYellow", "Yellow")
        ("TabColorPurple", "Purple")
        ("TabColorOrange", "Orange")
        ("TabColorPink", "Pink")
        ("TabColorRedUnderline", "Red Underline")
        ("TabColorBlueUnderline", "Blue Underline")
        ("TabColorGreenUnderline", "Green Underline")
        ("TabColorYellowUnderline", "Yellow Underline")
        ("TabColorPurpleUnderline", "Purple Underline")
        ("TabColorOrangeUnderline", "Orange Underline")
        ("TabColorPinkUnderline", "Pink Underline")
        ("TabColorRedBorder", "Red Border")
        ("TabColorBlueBorder", "Blue Border")
        ("TabColorGreenBorder", "Green Border")
        ("TabColorYellowBorder", "Yellow Border")
        ("TabColorPurpleBorder", "Purple Border")
        ("TabColorOrangeBorder", "Orange Border")
        ("TabColorPinkBorder", "Pink Border")

        ("TabNameEdit", "Tab Name")
        ("RenameTab", "Rename tab")
        ("ResetTabName", "Reset tab name")

        ("TabDetachAndSplit", "Tab Detach and Split")
        ("DetachAndMovePosTab", "Detach this tab and reposition")
        ("DetachTabSamePosition", "Same position")
        ("DetachAndDockingTabToGroup", "Detach this tab and link to another group")
        ("SplitRightTabsToPositionFormat", "Split right {0} tabs and reposition")
        ("SplitRightTabsToGroupFormat", "Split right {0} tabs and link to group")
        ("SplitLeftTabsToPositionFormat", "Split left {0} tabs and reposition")
        ("SplitLeftTabsToGroupFormat", "Split left {0} tabs and link to group")
        ("MoveTabGroupFormat", "{0} {1}: {2}")

        ("SettingsMenu", "Settings...")

        ("Settings", "Settings...")
        ("Disable", "Disable")
        ("RestartWindowTabs", "Restart WindowTabs")
        ("CloseWindowTabs", "Close WindowTabs")
    ]
