namespace Bemo

module Localization_en =
    let strings = dict [
        ("Appearance", "Appearance")
        ("Background Active", "Background Active")
        ("Background Flash", "Background Flash")
        ("Background Highlight", "Background Highlight")
        ("Background Normal", "Background Normal")
        ("Behavior", "Behavior")
        ("Border", "Border")
        ("RestartWindowTabs", "Restart WindowTabs")
        ("CloseWindowTabs", "Close WindowTabs")
        ("Disable", "Disable")
        ("Diagnostics", "Diagnostics")
        ("Edit", "Edit")
        ("enableAutoGrouping", "Auto Grouping")
        ("enableTabs", "Tabs")
        ("Feedback", "Feedback...")
        ("enableCtrlNumberHotKey", "Enable Ctrl+1, ...Ctrl+9 to active tab")
        ("enableHoverActivate", "Enable mouse hover to activate tab")
        ("Height", "Height (pixels)")
        ("hideInactiveTabs", "Fade out tabs on inactive windows")
        ("Indent Flipped", "Distance from edge when tabs down (pixels)")
        ("Indent Normal", "Distance from edge when tabs up (pixels)")
        ("isTabbingEnabledForAllProcessesByDefault", "Enable tabs for all programs by default")
        ("MatchType", "Match Type")
        ("Max Width", "Max Width (pixels)")
        ("Text Color", "Color")
        ("Name", "Name")
        ("New", "New")
        ("nextTab", "Next Tab")
        ("Overlap", "Overlap (pixels)")
        ("prevTab", "Previous Tab")
        ("Programs", "Programs")
        ("Refresh", "Refresh")
        ("Remove", "Remove")
        ("Reset", "Reset")
        ("DarkColor", "Dark Color")
        ("DarkBlueColor", "Dark Blue Color")
        ("LightColor", "Light Color")
        ("Restore", "Restore")
        ("runAtStartup", "Run WindowTabs at startup")
        ("Settings", "Settings...")
        ("Language", "Language")
        ("CloseTab", "Close tab")
        ("CloseTabsToTheRight", "Close tabs to the right")
        ("CloseTabsToTheRightFormat", "Close tabs to the right ({0} {1})")
        ("TabSingular", "Tab")
        ("TabPlural", "Tabs")
        ("CloseTabsToTheLeft", "Close tabs to the left")
        ("CloseTabsToTheLeftFormat", "Close tabs to the left ({0} {1})")
        ("CloseOtherTabs", "Close other tabs in this group")
        ("CloseAllTabs", "Close all tabs in this group")
        ("NewWindow", "New window")
        ("MakeTabsWider", "Make tabs wider")
        ("MakeTabsNarrower", "Make tabs narrower")
        ("makeTabsNarrowerByDefault", "Toggle tab width on active tab icon double-click")
        ("tabPositionByDefault", "Tab position")
        ("TabPosition", "Tab position")
        ("RenameTab", "Rename tab")
        ("RestoreTabName", "Restore tab name")
        ("SettingsMenu", "Settings...")
        ("DetachAndMovePosTab", "Detach and reposition tab")
        ("DetachTabSamePosition", "Same position")
        ("DetachTabMoveRight", "Display right edge")
        ("DetachTabMoveLeft", "Display left edge")
        ("DetachTabMoveTop", "Display top edge")
        ("DetachTabMoveBottom", "Display bottom edge")
        ("Display", "Display")
        ("Left", "Left")
        ("Right", "Right")
        ("Up", "Up")
        ("Down", "Down")
        ("Main", "Main")
        ("DetachAndDockingTabToGroup", "Detach and link tab to another group")
        ("MovePosTabGroup", "Reposition tab group")
        ("MoveTabGroupFormat", "{0} {1}: {2}")
        ("DockingTabGroupToGroup", "Link tab group to another group")
        ("AlignLeft", "Left")
        ("AlignCenter", "Center")
        ("AlignRight", "Right")
        ("hideTabsWhenDownByDefault", "Hide tabs when positioned at bottom")
        ("HideTabsWhenDown", "Hide tabs when positioned at bottom")
        ("hideTabsDelayMilliseconds", "Hide tabs when positioned at bottom - wait time (milliseconds)")
        ("HideNever", "Never hide")
        ("HideWhenDown", "Hide after specified time")
        ("HideOnDoubleClick", "Hide when double-clicking active tab")
        ("Title", "Title")
        ("Workspace", "Workspace")
        ("Font", "Segoe UI")
        ("MenuDarkMode", "Menu Dark Mode")
    ]
