namespace Bemo

module Localization_ja =
    let strings = dict [
        ("Appearance", "表示")
        ("Background Active", "背景(アクティブ)")
        ("Background Flash", "背景(点滅)")
        ("Background Highlight", "背景(ハイライト)")
        ("Background Normal", "背景(通常)")
        ("Behavior", "動作")
        ("Border", "枠線")
        ("RestartWindowTabs", "WindowTabs 再起動")
        ("CloseWindowTabs", "WindowTabs 終了")
        ("Diagnostics", "診断")
        ("Edit", "編集")
        ("enableAutoGrouping", "自動グループ化")
        ("enableTabs", "タブ")
        ("Feedback", "フィードバック")
        ("enableCtrlNumberHotKey", "Ctrl+1...+9 でタブをアクティブ化する")
        ("enableHoverActivate", "マウスホバーでタブ切替を有効にする")
        ("Height", "高さ(ピクセル)")
        ("hideInactiveTabs", "非アクティブウィンドウのタブを半透明にする")
        ("Indent Flipped", "タブが下方向の時の端からの距離(ピクセル)")
        ("Indent Normal", "タブが上方向の時の端からの距離(ピクセル)")
        ("isTabbingEnabledForAllProcessesByDefault", "全てのプログラムでタブを使う")
        ("MatchType", "一致区分")
        ("Max Width", "最長幅(ピクセル)")
        ("Text Color", "文字色")
        ("Name", "名称")
        ("New", "新規")
        ("nextTab", "次のタブ")
        ("Overlap", "重なり(ピクセル)")
        ("prevTab", "前のタブ")
        ("Programs", "プログラム")
        ("Refresh", "更新")
        ("Remove", "削除")
        ("Reset", "リセット")
        ("DarkColor", "ダークカラー")
        ("DarkBlueColor", "ダークブルーカラー")
        ("LightColor", "ライトカラー")
        ("Restore", "元に戻す")
        ("runAtStartup", "電源投入時にWindowTabsを起動")
        ("Settings", "設定")
        ("Language", "Language")
        ("CloseTab", "このタブを閉じる")
        ("CloseTabsToTheRight", "右のタブを閉じる")
        ("CloseTabsToTheRightFormat", "右のタブを閉じる({0}タブ)")
        ("TabSingular", "タブ")
        ("TabPlural", "タブ")
        ("CloseTabsToTheLeft", "左のタブを閉じる")
        ("CloseTabsToTheLeftFormat", "左のタブを閉じる({0}タブ)")
        ("CloseOtherTabs", "このタブグループの他のタブを閉じる")
        ("CloseAllTabs", "このタブグループの全てのタブを閉じる")
        ("NewWindow", "新規ウィンドウ")
        ("MakeTabsWider", "タブ幅を広げる")
        ("MakeTabsNarrower", "タブ幅をせばめる")
        ("makeTabsNarrowerByDefault", "タブ幅をせばめる")
        ("tabPositionByDefault", "タブ位置")
        ("TabPosition", "タブ位置")
        ("RenameTab", "タブ名の変更")
        ("RestoreTabName", "名前を戻す")
        ("SettingsMenu", "設定...")
        ("DetachTab", "タブの分離 / ウィンドウ移動")
        ("DetachTabSamePosition", "同じ位置で分離")
        ("DetachTabMoveRight", "ディスプレイの右端")
        ("DetachTabMoveLeft", "ディスプレイの左端")
        ("DetachTabMoveTop", "ディスプレイの上端")
        ("DetachTabMoveBottom", "ディスプレイの下端")
        ("Display", "ディスプレイ")
        ("Left", "左")
        ("Right", "右")
        ("Up", "上")
        ("Down", "下")
        ("Main", "メイン")
        ("MoveTab", "タブの移動")
        ("MoveTabGroupFormat", "{0}{1}: {2}")
        ("AlignLeft", "左")
        ("AlignCenter", "中央")
        ("AlignRight", "右")
        ("hideTabsWhenDownByDefault", "タブが下方向の時に隠す機能")
        ("HideTabsWhenDown", "タブが下方向の時に隠す機能")
        ("hideTabsDelayMilliseconds", "タブが下方向の時に隠す機能 待機時間(ミリ秒)")
        ("HideNever", "隠さない")
        ("HideWhenMaximized", "最大化の時のみ指定時間後に隠す")
        ("HideWhenDown", "常に指定時間後に隠す(最大化の時を含む)")
        ("HideOnDoubleClick", "アクティブタブをダブルクリック時に隠す")
        ("Title", "タイトル")
        ("Workspace", "ワークスペース")
        ("Font", "Segoe UI")
        ("MenuDarkMode", "メニューをダークモードにする")
    ]
